site_name: zelph - A Sophisticated Semantic Network System
theme:
  name: material
  palette:
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - navigation.expand
    - content.code.annotate
extra_css:
  - stylesheets/extra.css
nav:
  - Home: index.md
  - Logic and Computation: logic.md
  - Presentation: presentation.md
  - Quick Start Guide: quickstart.md
  - Performing Queries: queries.md
  - Scripting with Janet: janet.md
  - Importing and Exporting Data: import-export.md
  - Binary Data Files: binaries.md
  - Use Case - Wikidata: wikidata.md
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight
extra_javascript:
  - https://unpkg.com/mermaid@11.4.1/dist/mermaid.min.js
extra:
  mermaid:
    version: 11.4.1
exclude_docs: |
  missing-superclass/
